### ISSUE TITLE
Please make this repo private

### ISSUE THREAD

**Issue by MaddyGuthridge** [Revelrousdust01/Toohak#2]
Publishing the solution to a university assignment without explicit permission is a violation of UNSW's student code of conduct, as it facilitates cheating and plagiarism, which can have severe consequences. Please make this repository private, to avoid spoiling the assignment for other students.

**Comment by Revelrousdust01** [comment]
I understand, I will do this now. I do ask however if this auditing is also being applied to other people. There is like a dozen other Github repos that have a fully implemented solution as well?
